name: Disable Workflow

on:
 push: 
   branches: [main]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
       
     - name: Setup
       uses: actions/setup-node@v6.3.0
       with:
         node-version: 22.x
         cache: 'npm'
     - name: Install Dependencies
       run: npm run build

     - name: Build on Artifacts
       uses: actions/upload-artifact@v7.0.0
       with:
         name: Next js Build
         path: out/
         
       
      
     
     
       
     
 




